BTCPayServer/Models/ServerViewModels/EmailsViewModel.cs
using System.ComponentModel.DataAnnotations;
using BTCPayServer.Services.Mails;

namespace BTCPayServer.Models.ServerViewModels
{
    public class EmailsViewModel
    {
        public EmailsViewModel()
        {

        }
        public EmailsViewModel(EmailSettings settings)
        {
            Settings = settings;
            PasswordSet = !string.IsNullOrEmpty(settings?.Password);
        }
        public EmailSettings Settings
        {
            get; set;
        }
        public bool PasswordSet { get; set; }
        [EmailAddress]
        [Display(Name = "Test Email")]
        public string TestEmail
        {
            get; set;
        }
    }
}

BTCPayServer/Models/ServerViewModels/LightningWalletServices.cs
namespace BTCPayServer.Models.ServerViewModels
{
    public class LightningWalletServices
    {
        public string ServiceLink { get; set; }
        public bool ShowQR { get; set; }
        public string WalletName { get; internal set; }
    }
}

BTCPayServer/Models/ServerViewModels/LndSeedBackupViewModel.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace BTCPayServer.Models.ServerViewModels
{
    public class LndSeedBackupViewModel
    {
        public bool IsWalletUnlockPresent { get; set; }

        public string WalletPassword { get; set; }

        public string Seed { get; set; }

        public bool Removed { get; set; }
        public async Task<bool> RemoveSeedAndWrite(string lndSeedFilePath)
        {
            var removedDate = DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm:ssZ", CultureInfo.InvariantCulture);
            var seedFile = new LndSeedFile
            {
                wallet_password = WalletPassword,
                cipher_seed_mnemonic = new List<string> { $"Seed removed on {removedDate}" }
            };
            var json = JsonConvert.SerializeObject(seedFile);
            try
            {
                await File.WriteAllTextAsync(lndSeedFilePath, json);
                return true;
            }
            catch
            {
                // file access exception and such
                return false;
            }
        }


        public static LndSeedBackupViewModel Parse(string lndSeedFilePath)
        {
            try
            {
                if (!String.IsNullOrEmpty(lndSeedFilePath) && File.Exists(lndSeedFilePath))
                {
                    var unlockFileContents = File.ReadAllText(lndSeedFilePath);
                    var unlockFile = JsonConvert.DeserializeObject<LndSeedFile>(unlockFileContents);
#pragma warning disable CA1820 // Test for empty strings using string length
                    if (unlockFile.wallet_password == string.Empty)
#pragma warning restore CA1820 // Test for empty strings using string length
                    {
                        // Nicolas stupidinly deleted the password, so we should use the default one here...
                        unlockFile.wallet_password = "hellorockstar";
                    }
                    if (unlockFile.wallet_password != null)
                    {
                        return new LndSeedBackupViewModel
                        {
                            WalletPassword = unlockFile.wallet_password,
                            Seed = string.Join(' ', unlockFile.cipher_seed_mnemonic),
                            IsWalletUnlockPresent = true,
                            Removed = unlockFile.cipher_seed_mnemonic.Count == 1
                        };
                    }
                }
            }
            catch
            {
            }

            return new LndSeedBackupViewModel();
        }

        private class LndSeedFile
        {
            public string wallet_password { get; set; }
            public List<string> cipher_seed_mnemonic { get; set; }
        }
    }
}

BTCPayServer/Models/ServerViewModels/LndServicesViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace BTCPayServer.Models.ServerViewModels
{
    public class LndServicesViewModel
    {
        public string Host { get; set; }
        [Display(Name = "Use SSL")]
        public bool SSL { get; set; }
        public string Macaroon { get; set; }
        public string AdminMacaroon { get; set; }
        public string ReadonlyMacaroon { get; set; }
        public string InvoiceMacaroon { get; set; }
        public string CertificateThumbprint { get; set; }
        [Display(Name = "GRPC SSL Cipher suite (GRPC_SSL_CIPHER_SUITES)")]
        public string GRPCSSLCipherSuites { get; set; }
        public string QRCode { get; set; }
        public string QRCodeLink { get; set; }
        [Display(Name = "REST Uri")]
        public string Uri { get; set; }
        public string ConnectionType { get; internal set; }
    }
}

BTCPayServer/Models/ServerViewModels/LogsViewModel.cs
using System.Collections.Generic;
using System.IO;

namespace BTCPayServer.Models.ServerViewModels
{
    public class LogsViewModel
    {
        public List<FileInfo> LogFiles { get; set; } = new List<FileInfo>();
        public string Log { get; set; }
        public int LogFileCount { get; set; }
        public int LogFileOffset { get; set; }
    }
}

BTCPayServer/Models/ServerViewModels/MaintenanceViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace BTCPayServer.Models.ServerViewModels
{
    public class MaintenanceViewModel
    {
        [Display(Name = "Change domain")]
        public string DNSDomain { get; set; }
        public bool CanUseSSH { get; internal set; }
    }
}

BTCPayServer/Models/ServerViewModels/SSHServiceViewModel.cs
namespace BTCPayServer.Models.ServerViewModels
{
    public class SSHServiceViewModel
    {
        public string CommandLine { get; set; }
        public string Password { get; set; }
        public string KeyFilePassword { get; set; }
        public bool HasKeyFile { get; set; }
        public string SSHKeyFileContent { get; set; }
    }
}

BTCPayServer/Models/ServerViewModels/ServicesViewModel.cs
using System.Collections.Generic;
using BTCPayServer.Configuration;

namespace BTCPayServer.Models.ServerViewModels
{
    public class ServicesViewModel
    {

        public class OtherExternalService
        {
            public string Name { get; set; }
            public string Link { get; set; }
        }

        public List<ExternalService> ExternalServices { get; set; } = new List<ExternalService>();
        public List<OtherExternalService> OtherExternalServices { get; set; } = new List<OtherExternalService>();
        public List<OtherExternalService> TorHttpServices { get; set; } = new List<OtherExternalService>();
        public List<OtherExternalService> TorOtherServices { get; set; } = new List<OtherExternalService>();
        public List<OtherExternalService> ExternalStorageServices { get; set; } = new List<OtherExternalService>();
    }
}

BTCPayServer/Models/ServerViewModels/UsersViewModel.cs
using System;
using System.Collections.Generic;

namespace BTCPayServer.Models.ServerViewModels
{
    public class UsersViewModel : BasePagingViewModel
    {
        public class UserViewModel
        {
            public string Id { get; set; }
            public string Name { get; set; }
            public string Email { get; set; }
            public bool Verified { get; set; }
            public bool IsAdmin { get; set; }
            public DateTimeOffset? Created { get; set; }
            public IEnumerable<string> Roles { get; set; }
        }
        public List<UserViewModel> Users { get; set; } = new List<UserViewModel>();
        public Dictionary<string, string> Roles { get; set; }
    }

}

BTCPayServer/Controllers/UIServerController.cs
#nullable enable
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mail;
using System.Threading.Tasks;
using BTCPayServer.Abstractions.Constants;
using BTCPayServer.Abstractions.Extensions;
using BTCPayServer.Abstractions.Models;
using BTCPayServer.Configuration;
using BTCPayServer.Data;
using BTCPayServer.HostedServices;
using BTCPayServer.Hosting;
using BTCPayServer.Logging;
using BTCPayServer.Models;
using BTCPayServer.Models.ServerViewModels;
using BTCPayServer.Services;
using BTCPayServer.Services.Apps;
using BTCPayServer.Services.Mails;
using BTCPayServer.Services.Stores;
using BTCPayServer.Storage.Models;
using BTCPayServer.Storage.Services;
using BTCPayServer.Storage.Services.Providers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Routing;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using MimeKit;
using NBitcoin;
using NBitcoin.DataEncoders;
using Renci.SshNet;
using AuthenticationSchemes = BTCPayServer.Abstractions.Constants.AuthenticationSchemes;

namespace BTCPayServer.Controllers
{
    [Authorize(Policy = BTCPayServer.Client.Policies.CanModifyServerSettings,
               AuthenticationSchemes = AuthenticationSchemes.Cookie)]
    public partial class UIServerController : Controller
    {
        private readonly UserManager<ApplicationUser> _UserManager;
        private readonly UserService _userService;
        readonly SettingsRepository _SettingsRepository;
        private readonly NBXplorerDashboard _dashBoard;
        private readonly StoreRepository _StoreRepository;
        readonly LightningConfigurationProvider _LnConfigProvider;
        private readonly TorServices _torServices;
        private readonly BTCPayServerOptions _Options;
        private readonly AppService _AppService;
        private readonly CheckConfigurationHostedService _sshState;
        private readonly EventAggregator _eventAggregator;
        private readonly IOptions<ExternalServicesOptions> _externalServiceOptions;
        private readonly Logs Logs;
        private readonly StoredFileRepository _StoredFileRepository;
        private readonly FileService _FileService;
        private readonly IEnumerable<IStorageProviderService> _StorageProviderServices;

        public UIServerController(
            UserManager<ApplicationUser> userManager,
            UserService userService,
            StoredFileRepository storedFileRepository,
            FileService fileService,
            IEnumerable<IStorageProviderService> storageProviderServices,
            BTCPayServerOptions options,
            SettingsRepository settingsRepository,
            NBXplorerDashboard dashBoard,
            IHttpClientFactory httpClientFactory,
            LightningConfigurationProvider lnConfigProvider,
            TorServices torServices,
            StoreRepository storeRepository,
            AppService appService,
            CheckConfigurationHostedService sshState,
            EventAggregator eventAggregator,
            IOptions<ExternalServicesOptions> externalServiceOptions,
            Logs logs)
        {
            _Options = options;
            _StoredFileRepository = storedFileRepository;
            _FileService = fileService;
            _StorageProviderServices = storageProviderServices;
            _UserManager = userManager;
            _userService = userService;
            _SettingsRepository = settingsRepository;
            _dashBoard = dashBoard;
            HttpClientFactory = httpClientFactory;
            _StoreRepository = storeRepository;
            _LnConfigProvider = lnConfigProvider;
            _torServices = torServices;
            _AppService = appService;
            _sshState = sshState;
            _eventAggregator = eventAggregator;
            _externalServiceOptions = externalServiceOptions;
            Logs = logs;
        }

        [Route("server/maintenance")]
        public IActionResult Maintenance()
        {
            MaintenanceViewModel vm = new MaintenanceViewModel();
            vm.CanUseSSH = _sshState.CanUseSSH;
            if (!vm.CanUseSSH)
                TempData[WellKnownTempData.ErrorMessage] = "Maintenance feature requires access to SSH properly configured in BTCPay Server configuration.";
            vm.DNSDomain = this.Request.Host.Host;
            if (IPAddress.TryParse(vm.DNSDomain, out var unused))
                vm.DNSDomain = null;
            return View(vm);
        }

        [Route("server/maintenance")]
        [HttpPost]
        public async Task<IActionResult> Maintenance(MaintenanceViewModel vm, string command)
        {
            vm.CanUseSSH = _sshState.CanUseSSH;

            if (!vm.CanUseSSH)
            {
                TempData[WellKnownTempData.ErrorMessage] = "Maintenance feature requires access to SSH properly configured in BTCPay Server configuration.";
                return View(vm);
            }
            if (!ModelState.IsValid)
                return View(vm);
            if (command == "changedomain")
            {
                if (string.IsNullOrWhiteSpace(vm.DNSDomain))
                {
                    ModelState.AddModelError(nameof(vm.DNSDomain), $"Required field");
                    return View(vm);
                }
                vm.DNSDomain = vm.DNSDomain.Trim().ToLowerInvariant();
                if (vm.DNSDomain.Equals(this.Request.Host.Host, StringComparison.OrdinalIgnoreCase))
                    return View(vm);
                if (IPAddress.TryParse(vm.DNSDomain, out var unused))
                {
                    ModelState.AddModelError(nameof(vm.DNSDomain), $"This should be a domain name");
                    return View(vm);
                }
                if (vm.DNSDomain.Equals(this.Request.Host.Host, StringComparison.InvariantCultureIgnoreCase))
                {
                    ModelState.AddModelError(nameof(vm.DNSDomain), $"The server is already set to use this domain");
                    return View(vm);
                }
                var builder = new UriBuilder();
                using (var client = new HttpClient(new HttpClientHandler()
                {
                    ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator
                }))
                {
                    try
                    {
                        builder.Scheme = this.Request.Scheme;
                        builder.Host = vm.DNSDomain;
                        var addresses1 = GetAddressAsync(this.Request.Host.Host);
                        var addresses2 = GetAddressAsync(vm.DNSDomain);
                        await Task.WhenAll(addresses1, addresses2);

                        var addressesSet = addresses1.GetAwaiter().GetResult().Select(c => c.ToString()).ToHashSet();
                        var hasCommonAddress = addresses2.GetAwaiter().GetResult().Select(c => c.ToString()).Any(s => addressesSet.Contains(s));
                        if (!hasCommonAddress)
                        {
                            ModelState.AddModelError(nameof(vm.DNSDomain), $"Invalid host ({vm.DNSDomain} is not pointing to this BTCPay instance)");
                            return View(vm);
                        }
                    }
                    catch (Exception ex)
                    {
                        var messages = new List<object>();
                        messages.Add(ex.Message);
                        if (ex.InnerException != null)
                            messages.Add(ex.InnerException.Message);
                        ModelState.AddModelError(nameof(vm.DNSDomain), $"Invalid domain ({string.Join(", ", messages.ToArray())})");
                        return View(vm);
                    }
                }

                var error = await RunSSH(vm, $"changedomain.sh {vm.DNSDomain}");
                if (error != null)
                    return error;

                builder.Path = null;
                builder.Query = null;
                TempData[WellKnownTempData.SuccessMessage] = $"Domain name changing... the server will restart, please use \"{builder.Uri.AbsoluteUri}\" (this page won't reload automatically)";
            }
            else if (command == "update")
            {
                var error = await RunSSH(vm, $"btcpay-update.sh");
                if (error != null)
                    return error;
                TempData[WellKnownTempData.SuccessMessage] = $"The server might restart soon if an update is available...  (this page won't reload automatically)";
            }
            else if (command == "clean")
            {
                var error = await RunSSH(vm, $"btcpay-clean.sh");
                if (error != null)
                    return error;
                TempData[WellKnownTempData.SuccessMessage] = $"The old docker images will be cleaned soon...";
            }
            else if (command == "restart")
            {
                var error = await RunSSH(vm, $"btcpay-restart.sh");
                if (error != null)
                    return error;
                TempData[WellKnownTempData.SuccessMessage] = $"BTCPay will restart momentarily.";
            }
            else
            {
                return NotFound();
            }
            return RedirectToAction(nameof(Maintenance));
        }

        private Task<IPAddress[]> GetAddressAsync(string domainOrIP)
        {
            if (IPAddress.TryParse(domainOrIP, out var ip))
                return Task.FromResult(new[] { ip });
            return Dns.GetHostAddressesAsync(domainOrIP);
        }

        public static string RunId = Encoders.Hex.EncodeData(NBitcoin.RandomUtils.GetBytes(32));

BTCPayServer/Views/UIServer/ConfiguratorService.cshtml
@model LightningWalletServices
@{
    ViewData.SetActivePage(ServerNavPages.Services, "BTCPay Server Configurator");
}

<h3 class="mb-4">@ViewData["Title"]</h3>

<div class="row">
    <div class="col-md-6">
        <div asp-validation-summary="All" class="text-danger"></div>
    </div>
</div>

<div class="row">
    <div class="col-md-8">
        <div class="form-group">
            <p>
                <span>This page exposes information to use the configured BTCPay Server Configurator to modify this setup.</span>
            </p>
        </div>
       
        <a href="@Model.ServiceLink" target="_blank" class="form-group" rel="noreferrer noopener">
            <label asp-for="ServiceLink" class="form-label">Service</label>
            <input asp-for="ServiceLink" class="form-control" readonly />
        </a>
    </div>
</div>

@section PageFootContent {
    <partial name="_ValidationScriptsPartial" />
}

BTCPayServer/Views/UIServer/Emails.cshtml
@model EmailsViewModel
@{
    ViewData.SetActivePage(ServerNavPages.Emails, "Email Server");
}

<partial name="EmailsBody" model="Model" />

@section PageFootContent {
    <partial name="_ValidationScriptsPartial" />
}

BTCPayServer/Views/UIServer/Policies.cshtml
@using BTCPayServer.Services
@using BTCPayServer.Services.Mails;
@model BTCPayServer.Services.PoliciesSettings
@inject SettingsRepository _SettingsRepository
@{
    ViewData.SetActivePage(ServerNavPages.Policies);
}

<h3 class="mb-4">@ViewData["Title"]</h3>

@if (!ViewContext.ModelState.IsValid)
{
    <div asp-validation-summary="All" class="text-danger"></div>
}

<form method="post">
    <div class="form-group mb-5">
        <h4 class="mb-3">Existing User Settings</h4>
        <div class="form-check my-1">
            <input asp-for="AllowLightningInternalNodeForAll" type="checkbox" class="form-check-input"/>
            <label asp-for="AllowLightningInternalNodeForAll" class="form-check-label"></label>
            <a href="https://docs.btcpayserver.org/FAQ/LightningNetwork/#how-many-users-can-use-lightning-network-in-btcpay" target="_blank" rel="noreferrer noopener">
                <span class="fa fa-question-circle-o text-secondary" title="More information..."></span>
            </a>
            <span asp-validation-for="AllowLightningInternalNodeForAll" class="text-danger"></span>
        </div>
        <div class="form-check my-1">
            <input asp-for="AllowHotWalletForAll" type="checkbox" class="form-check-input"/>
            <label asp-for="AllowHotWalletForAll" class="form-check-label"></label>
            <a href="https://docs.btcpayserver.org/CreateWallet/#requirements-to-create-wallets" target="_blank" rel="noreferrer noopener">
                <span class="fa fa-question-circle-o text-secondary" title="More information..."></span>
            </a>
            <span asp-validation-for="AllowHotWalletForAll" class="text-danger"></span>
        </div>
        <div class="form-check my-1">
            <input asp-for="AllowHotWalletRPCImportForAll" type="checkbox" class="form-check-input"/>
            <label asp-for="AllowHotWalletRPCImportForAll" class="form-check-label"></label>
            <span asp-validation-for="AllowHotWalletRPCImportForAll" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group mb-5">
        <h4 class="mb-3">New User Settings</h4>
        <div class="form-check my-1">
            @{
                var emailSettings = (await _SettingsRepository.GetSettingAsync<EmailSettings>()) ?? new EmailSettings();
                /* The "|| Model.RequiresConfirmedEmail" check is for the case when a user had checked
                   the checkbox without first configuring the e-mail settings so that they can uncheck it. */
                var isEmailConfigured = emailSettings.IsComplete() || Model.RequiresConfirmedEmail;
            }
            <input asp-for="RequiresConfirmedEmail" type="checkbox" class="form-check-input" disabled="@(isEmailConfigured ? null : "disabled")"/>
            <label asp-for="RequiresConfirmedEmail" class="form-check-label"></label>
            <a href="https://docs.btcpayserver.org/FAQ/ServerSettings/#how-to-allow-registration-on-my-btcpay-server" target="_blank" rel="noreferrer noopener">
                <span class="fa fa-question-circle-o text-secondary" title="More information..."></span>
            </a>
            <span asp-validation-for="RequiresConfirmedEmail" class="text-danger"></span>
            @if (!isEmailConfigured)
            {
                <div class="mb-2">
                    <span class="text-secondary">Your email server has not been configured. <a asp-controller="UIServer" asp-action="Emails">Please configure it first.</a></span>
                </div>
            }
        </div>
        <div class="form-check my-1">
            <input asp-for="LockSubscription" type="checkbox" class="form-check-input"/>
            <label asp-for="LockSubscription" class="form-check-label"></label>
            <span asp-validation-for="LockSubscription" class="text-danger"></span>
        </div>

        <div class="form-check my-1">
            <input asp-for="DisableNonAdminCreateUserApi" type="checkbox" class="form-check-input"/>
            <label asp-for="DisableNonAdminCreateUserApi" class="form-check-label"></label>
            <span asp-validation-for="DisableNonAdminCreateUserApi" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group mb-5">
        <h4 class="mb-3">Notification Settings</h4>
        <div class="form-check my-1">
            <input asp-for="DisableInstantNotifications" type="checkbox" class="form-check-input"/>
            <label asp-for="DisableInstantNotifications" class="form-check-label"></label>
            <a href="https://docs.btcpayserver.org/Notifications/#notifications" target="_blank" rel="noreferrer noopener">
                <span class="fa fa-question-circle-o text-secondary" title="More information..."></span>
            </a>
            <span asp-validation-for="DisableInstantNotifications" class="text-danger"></span>
        </div>
        <div class="form-check my-1">
            <input asp-for="DisableStoresToUseServerEmailSettings" type="checkbox" class="form-check-input"/>
            <label asp-for="DisableStoresToUseServerEmailSettings" class="form-check-label"></label>
            <a href="https://docs.btcpayserver.org/Notifications/#server-emails" target="_blank" rel="noreferrer noopener">
                <span class="fa fa-question-circle-o text-secondary" title="More information..."></span>
            </a>
            <span asp-validation-for="DisableStoresToUseServerEmailSettings" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group mb-5">
        <h4 class="mb-3">Maintenance Settings</h4>
        @if (ViewBag.UpdateUrlPresent)
        {
            <div class="form-check my-1">
                <input asp-for="CheckForNewVersions" type="checkbox" class="form-check-input"/>
                <label asp-for="CheckForNewVersions" class="form-check-label"></label>
                <span asp-validation-for="CheckForNewVersions" class="text-danger"></span>
            </div>
        }
        <div class="form-check my-1">
            <input asp-for="DiscourageSearchEngines" type="checkbox" class="form-check-input"/>
            <label asp-for="DiscourageSearchEngines" class="form-check-label"></label>
            <a href="https://docs.btcpayserver.org/FAQ/ServerSettings/#how-to-hide-my-btcpay-server-from-search-engines" target="_blank" rel="noreferrer noopener">
                <span class="fa fa-question-circle-o text-secondary" title="More information..."></span>
            </a>
            <span asp-validation-for="DiscourageSearchEngines" class="text-danger"></span>
        </div>
    </div>

    <h4 class="mb-3">Customization Settings</h4>

    <div class="form-group">
        <label asp-for="RootAppId" class="form-label"></label>
        <select asp-for="RootAppId" asp-items="@(new SelectList(ViewBag.AppsList, nameof(SelectListItem.Value), nameof(SelectListItem.Text), Model.RootAppId))" class="form-select w-auto"></select>
        @if (!Model.DomainToAppMapping.Any())
        {
            <button id="AddDomainButton" type="submit" name="command" value="add-domain" class="btn btn-link px-0">Map specific domains to specific apps</button>
        }
    </div>

    @if (Model.DomainToAppMapping.Any())
    {
        <h5 class="mt-5 mb-0">
            Domain to app mapping
            <button id="AddDomainButton" type="submit" name="command" value="add-domain" class="btn btn-secondary btn-sm ms-2">Add domain mapping</button>
        </h5>
        <div class="list-group list-group-flush mb-2">
            @for (var index = 0; index < Model.DomainToAppMapping.Count; index++)
            {
                <div class="list-group-item px-0 pt-3">
                    <div class="row">
                        <div class="col-12 col-lg-8">
                            <div class="form-group">
                                <label asp-for="DomainToAppMapping[index].Domain" class="form-label"></label>
                                <input asp-for="DomainToAppMapping[index].Domain" class="form-control"/>
                                <span asp-validation-for="DomainToAppMapping[index].Domain" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="DomainToAppMapping[index].AppId" class="form-label"></label>
                                <select asp-for="DomainToAppMapping[index].AppId"
                                        asp-items="@(new SelectList(ViewBag.AppsList, nameof(SelectListItem.Value), nameof(SelectListItem.Text), Model.DomainToAppMapping[index].AppId))"
                                        class="form-select w-auto">
                                </select>
                                <span asp-validation-for="DomainToAppMapping[index].AppId" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-12 col-lg-2 pull-right">
                            <button type="submit" title="Remove domain mapping" name="command" value="@($"remove-domain:{index}")"
                                    class="d-block d-lg-none d-xl-none btn btn-danger mb-2">
                                Remove Destination
                            </button>
                            <button type="submit" title="Remove domain mapping" name="command" value="@($"remove-domain:{index}")"
                                    class="d-none d-lg-block btn btn-outline-danger text-decoration-none h-100 align-middle border-0 fs-4">
                                <span class="fa fa-times"></span>
                            </button>
                        </div>
                    </div>
                </div>
            }
        </div>
    }

    <button class="btn btn-link px-0" type="button" id="ExplorerLinksButton" data-bs-toggle="collapse" data-bs-target="#explorer-links" aria-expanded="false" aria-controls="explorer-links">
        Override the block explorers used
    </button>

    <div class="mb-3">
        <div class="collapse show collapse-on-js" id="explorer-links">
            @inject BTCPayNetworkProvider BTCPayNetworkProvider
            @{
                var networks = BTCPayNetworkProvider.GetAll().ToArray();
            }

            @for (var i = 0; i < networks.Count(); i++)
            {
                var network = networks.ElementAt(i);
                var existingOverride = Model.BlockExplorerLinks?.SingleOrDefault(tuple => tuple.CryptoCode.Equals(network.CryptoCode, StringComparison.InvariantCultureIgnoreCase));
                var linkValue = existingOverride?.Link ?? network.BlockExplorerLinkDefault;
                if (Model.BlockExplorerLinks.Count < i + 1)
                {
                    Model.BlockExplorerLinks.Add(new PoliciesSettings.BlockExplorerOverrideItem() {CryptoCode = network.CryptoCode, Link = network.BlockExplorerLinkDefault});
                }
                <div class="form-group m-0 py-4">
                    <label class="form-label">@network.DisplayName (@network.CryptoCode)</label>
                    <input type="hidden" asp-for="BlockExplorerLinks[i].CryptoCode" value="@network.CryptoCode"/>
                    <div class="input-group">
                        <input type="text" class="form-control" asp-for="BlockExplorerLinks[i].Link" value="@linkValue" rel="noreferrer noopener" data-default-link="@network.BlockExplorerLinkDefault"/>
                        <button type="button" class="btn btn-secondary only-for-js" title="Revert to default">
                            <span class="fa fa-refresh"></span>
                        </button>
                    </div>
                </div>
            }
        </div>
    </div>

    <button id="SaveButton" type="submit" class="btn btn-primary" name="command" value="Save">Save</button>
</form>

@section PageFootContent {
    <script>
        for (let element of document.getElementsByClassName("revert-default")) {
            element.addEventListener("click", function (){
              element.parentElement.previousElementSibling.value = element.parentElement.previousElementSibling.getAttribute("data-default-link")
            });
        }
        for (let element of document.getElementsByClassName("collapse-on-js")){
            if (element.classList.contains("show")){
                element.classList.remove("show");
            }    
        }
    </script>
}